# Generated by Django 5.2.1 on 2025-06-24 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('uz', 'O‘zbekcha')], max_length=2)),
                ('service', models.CharField(choices=[('website', 'Веб-сайт'), ('telegram_bot', 'Telegram-бот'), ('banner', 'Баннер'), ('logo', 'Логотип'), ('typography', 'Типография'), ('other', 'Другое')], max_length=50)),
                ('subservice', models.CharField(max_length=255)),
                ('tariff', models.CharField(choices=[('standard', 'Стандарт'), ('premium', 'Премиум')], max_length=10)),
                ('price', models.CharField(default='Договорная', max_length=50)),
                ('telegram_username', models.CharField(blank=True, max_length=255)),
                ('telegram_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
