# Generated by Django 5.2.1 on 2025-06-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramorder',
            name='service',
            field=models.CharField(choices=[('website', 'Веб-сайт'), ('telegram_bot', 'Телеграм-бот'), ('banner', 'Баннер'), ('logo', 'Логотип'), ('print', 'Типография')], max_length=50),
        ),
    ]
