# Generated by Django 5.2.1 on 2025-06-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_orders', '0003_telegramrequest_delete_telegramorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('username', models.CharField(blank=True, max_length=255)),
                ('is_welcomed', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
