# Generated by Django 5.2.1 on 2025-06-23 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_yourmodel_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='yourmodel',
            options={'verbose_name': 'Локация text для сайта', 'verbose_name_plural': 'Локация text для сайта'},
        ),
    ]
