# Generated by Django 5.2.1 on 2025-06-22 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calendarevent',
            options={'verbose_name': 'Календарь', 'verbose_name_plural': 'Календарь'},
        ),
    ]
