# Generated by Django 5.2.1 on 2025-06-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammember',
            options={'verbose_name': 'Наша команда', 'verbose_name_plural': 'Наша команда'},
        ),
        migrations.AlterField(
            model_name='teammember',
            name='age',
            field=models.PositiveIntegerField(verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Когда создан'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='facebook_link',
            field=models.URLField(blank=True, null=True, verbose_name='facebook_aккоунт'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='Полное Имя'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='instagram_link',
            field=models.URLField(blank=True, null=True, verbose_name='instagram_aккоунт'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(upload_to='team_photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='profession',
            field=models.CharField(max_length=255, verbose_name='Профессия'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='telegram_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телеграмма_Номер'),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя_Пользователя_Телеграммы'),
        ),
    ]
