# Generated by Django 5.2.1 on 2025-06-24 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_applicationform_delete_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationform',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
