# Generated by Django 5.2.1 on 2025-06-23 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': 'Карточна товора', 'verbose_name_plural': 'Карточна товора'},
        ),
    ]
