# Generated by Django 5.2.1 on 2025-06-23 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('sold_this_week', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
