# Generated by Django 5.2.1 on 2025-06-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sold_this_week',
            field=models.PositiveIntegerField(default=0, verbose_name='продано_на_этой_неделе'),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='общее_количество'),
        ),
    ]
