# Generated by Django 5.2.1 on 2025-06-23 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_product_name_alter_product_sold_this_week_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар скидка', 'verbose_name_plural': 'Товар скидка'},
        ),
    ]
