# Generated by Django 5.2.1 on 2025-06-23 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category_title', '0002_alter_categorytitle_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorytitle',
            options={'verbose_name': 'Товарная катерогия', 'verbose_name_plural': 'Товарная катерогия'},
        ),
    ]
