# Generated by Django 5.2.1 on 2025-06-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('region', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('apartment', models.CharField(blank=True, max_length=100)),
                ('delivery_method', models.CharField(choices=[('delivery', 'Etkazib berish'), ('pickup', 'Doʻkondan olib ketish')], max_length=20)),
                ('delivery_type', models.CharField(choices=[('standard', 'Ertaga yoki keyinroq'), ('fast', 'Tez yetkazib berish')], max_length=20)),
                ('payment_method', models.CharField(choices=[('payme', 'Payme'), ('click', 'Click'), ('card', 'Onlayn karta orqali'), ('cod', 'Qabul qilinganda'), ('installment', 'Muddatli toʻlov')], max_length=20)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
